# Site settings
title: jflanagan again
description: > # this means to ignore newlines until "baseurl:"
  Longer-form thoughts from Joshua Flanagan, a software developer in Austin, TX
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://www.joshuaflanagan.com/blog" # the base hostname & protocol for your site
website: "http://www.joshuaflanagan.com"
twitter_username: jflanagan
github_username: joshuaflanagan

# Build settings
markdown: kramdown
